### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by iib0011** [altenull/json-sea#19]
Hi @altenull . I want to contribute. Can you document the project or create issues so I can help?

**Comment by altenull** [comment]
@iib0011 
Sure. I'm preparing some documents (e.g. README.md, release note).
I'll mention you when it is done. Thanks for your interest.

**Comment by altenull** [comment]
@iib0011
I just finished documentation. You can now view the README and create issue with issue templates.

**Comment by iib0011** [comment]
@altenull Create issues if you have, for me to start working on them
