### ISSUE TITLE
[FEATURE] Pls add mini map component

### ISSUE THREAD

**Issue by AlexSKuznetsov** [altenull/json-sea#20]
### Describe the feature

Pls, add a mini-map component so I can easily navigate through the big JSON files.

https://reactflow.dev/docs/api/plugin-components/minimap/

**Comment by altenull** [comment]
@AlexSKuznetsov
That's cool. I'll include this feature in the next release.

**Comment by altenull** [comment]
@AlexSKuznetsov
New version is just released including mini-map component you requested.
